### ISSUE TITLE
Failed to open Log Viewer from console: unable to load resource ProcessConsole\JettyApp [Java Application] ...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [anb0s/LogViewer#76]
```
What steps will reproduce the problem?
1. Start a Java application (like jetty) on Eclipse and console window shows 
the app logs;
2. The console name or title shows like "JettyApp [Java Application] 
C:\Java\jdk1.6.0_45\bin\javaw.exe (Dec 12, 2013, 10:54:14 AM)"
3. Click Open with Log View but it shows:

WARNING: resource 
org.eclipse.debug.internal.ui.views.console.ProcessConsole\JettyApp [Java 
Application] C:\Java\jdk1.6.0_45\bin\javaw.exe (Dec 11, 2013, 6:01:44 PM) 
(temporarily) not available ...

Eclipse workspace/.metadata/.log file recorded the exception:

de.anbos.eclipse.logviewer.plugin.file.ThreadInterruptedException: no console 
found
    at de.anbos.eclipse.logviewer.plugin.file.ConsoleTail.openConsole(ConsoleTail.java:169)
    at de.anbos.eclipse.logviewer.plugin.file.ConsoleTail.run(ConsoleTail.java:107)
    at java.lang.Thread.run(Unknown Source)

==
Log Viewer version: 0.9.8.8
Eclipse version: Kepler, v4.3.1
Java SDK version: Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed 
mode)
Operation system: Windows 7 SP1

==
When open other console like SVN Console or Maven Console with Log Viewer, it 
works find but when start a Java application and the console title is too long 
like containing the JDK path, it seems failed to load the ProcessConsole by the 
console name...
```

Original issue reported on code.google.com by `jacky...@gmail.com` on 12 Dec 2013 at 3:23

**Comment by anb0s** [comment]
issue #65

**Comment by anb0s** [comment]
fixed
